server:
   port: 9797
   servlet:
      context-path: /vm-provisioner
spring:
   application:
      name: vm-provisioner
   datasource:
      url: jdbc:postgresql://localhost:5432/vm_provisioner
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
         ddl-auto: none
      open-in-view: true
   liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yml
logging:
   level:
      liquibase: error

